### ISSUE TITLE
SVG not working

### ISSUE THREAD

**Issue by laszlokorte** [tsers-js/snabbdom#2]
I just tried to create my first TSERS component using SVG.

https://gist.github.com/laszlokorte/2a9ae0accca2805bde3eb28c376fd660#file-tsers-component-js-L11-L13

The `width` and `height` attributes of the svg tag itself get set but the `cx`, `cy` and `r` attributes of the circle tag are not set.

I think the reason is this check:
https://github.com/tsers-js/snabbdom/blob/master/src/index.js#L104-L107
which tries to unify snabbdoms `props` and `attrs` options.

**Comment by milankinen** [comment]
Nice notice! SVG implementation is indeed missing ATM. I created tsers-js/core#15 to track this issue.
